// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceTurnReducer from "../advance_turn_reducer";
import ClaimMentorSeatReducer from "../claim_mentor_seat_reducer";
import CreateRoomReducer from "../create_room_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import PostQuestionReducer from "../post_question_reducer";
import PushFrameReducer from "../push_frame_reducer";
import StartSessionReducer from "../start_session_reducer";
import SubmitAnswerReducer from "../submit_answer_reducer";
import SubmitFeedbackReducer from "../submit_feedback_reducer";

export type AdvanceTurnParams = __Infer<typeof AdvanceTurnReducer>;
export type ClaimMentorSeatParams = __Infer<typeof ClaimMentorSeatReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type PostQuestionParams = __Infer<typeof PostQuestionReducer>;
export type PushFrameParams = __Infer<typeof PushFrameReducer>;
export type StartSessionParams = __Infer<typeof StartSessionReducer>;
export type SubmitAnswerParams = __Infer<typeof SubmitAnswerReducer>;
export type SubmitFeedbackParams = __Infer<typeof SubmitFeedbackReducer>;

