// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CastVoteReducer from "../cast_vote_reducer";
import ClaimFileReducer from "../claim_file_reducer";
import ClaimIntentReducer from "../claim_intent_reducer";
import CreateRoomReducer from "../create_room_reducer";
import DeleteFileReducer from "../delete_file_reducer";
import FinishBuildReducer from "../finish_build_reducer";
import GradeDeterministicReducer from "../grade_deterministic_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import InitRaceTeamsReducer from "../init_race_teams_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import LoadBenchTaskReducer from "../load_bench_task_reducer";
import MarkIntentReducer from "../mark_intent_reducer";
import PostActivityReducer from "../post_activity_reducer";
import PushFrameReducer from "../push_frame_reducer";
import RecordVerdictReducer from "../record_verdict_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import ReleaseFileReducer from "../release_file_reducer";
import SetAgentStatusReducer from "../set_agent_status_reducer";
import SetFileOwnerReducer from "../set_file_owner_reducer";
import StartBuildReducer from "../start_build_reducer";
import SubmitIntentReducer from "../submit_intent_reducer";
import WriteFileReducer from "../write_file_reducer";

export type CastVoteParams = __Infer<typeof CastVoteReducer>;
export type ClaimFileParams = __Infer<typeof ClaimFileReducer>;
export type ClaimIntentParams = __Infer<typeof ClaimIntentReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DeleteFileParams = __Infer<typeof DeleteFileReducer>;
export type FinishBuildParams = __Infer<typeof FinishBuildReducer>;
export type GradeDeterministicParams = __Infer<typeof GradeDeterministicReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type InitRaceTeamsParams = __Infer<typeof InitRaceTeamsReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type LoadBenchTaskParams = __Infer<typeof LoadBenchTaskReducer>;
export type MarkIntentParams = __Infer<typeof MarkIntentReducer>;
export type PostActivityParams = __Infer<typeof PostActivityReducer>;
export type PushFrameParams = __Infer<typeof PushFrameReducer>;
export type RecordVerdictParams = __Infer<typeof RecordVerdictReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type ReleaseFileParams = __Infer<typeof ReleaseFileReducer>;
export type SetAgentStatusParams = __Infer<typeof SetAgentStatusReducer>;
export type SetFileOwnerParams = __Infer<typeof SetFileOwnerReducer>;
export type StartBuildParams = __Infer<typeof StartBuildReducer>;
export type SubmitIntentParams = __Infer<typeof SubmitIntentReducer>;
export type WriteFileParams = __Infer<typeof WriteFileReducer>;

