// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  identity: __t.option(__t.identity()),
  authorName: __t.string().name("author_name"),
  actorKind: __t.string().name("actor_kind"),
  kind: __t.string(),
  text: __t.string(),
  path: __t.option(__t.string()),
  intentId: __t.option(__t.u64()).name("intent_id"),
  fromVersion: __t.option(__t.u64()).name("from_version"),
  toVersion: __t.option(__t.u64()).name("to_version"),
  createdAt: __t.timestamp().name("created_at"),
});
