// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  identity: __t.identity(),
  pairedHuman: __t.option(__t.identity()).name("paired_human"),
  team: __t.string(),
  role: __t.string(),
  displayName: __t.string().name("display_name"),
  status: __t.string(),
  busyIntentId: __t.option(__t.u64()).name("busy_intent_id"),
  updatedAt: __t.timestamp().name("updated_at"),
});
