// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  path: __t.string(),
  content: __t.string(),
  language: __t.string(),
  version: __t.u64(),
  ownerRole: __t.string().name("owner_role"),
  lockedBy: __t.option(__t.identity()).name("locked_by"),
  lockedAt: __t.option(__t.timestamp()).name("locked_at"),
  deleted: __t.bool(),
  lastEditedBy: __t.identity().name("last_edited_by"),
  lastEditedByName: __t.string().name("last_edited_by_name"),
  lastEditKind: __t.string().name("last_edit_kind"),
  updatedAt: __t.timestamp().name("updated_at"),
});
