// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  authorIdentity: __t.identity().name("author_identity"),
  authorName: __t.string().name("author_name"),
  targetAgentId: __t.u64().name("target_agent_id"),
  targetPath: __t.option(__t.string()).name("target_path"),
  text: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
