// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roomId: __t.u64(),
  teamId: __t.u64(),
  method: __t.string(),
  verified: __t.bool(),
  passed: __t.bool(),
  passedCount: __t.u32(),
  totalCount: __t.u32(),
  score: __t.f64(),
  stdout: __t.string(),
  stderr: __t.string(),
  durationMs: __t.u32(),
  judgeNotes: __t.string(),
};
