// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  teamId: __t.u64().primaryKey().name("team_id"),
  roomId: __t.u64().name("room_id"),
  bestScore: __t.f64().name("best_score"),
  bestPassed: __t.bool().name("best_passed"),
  attempts: __t.u32(),
  firstPassAttempt: __t.option(__t.u32()).name("first_pass_attempt"),
  firstPassAtMicros: __t.option(__t.i64()).name("first_pass_at_micros"),
  votes: __t.u32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
