// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Answer = __t.object("Answer", {
  id: __t.u64(),
  questionId: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  text: __t.string(),
  submittedAt: __t.timestamp(),
});
export type Answer = __Infer<typeof Answer>;

export const Feedback = __t.object("Feedback", {
  id: __t.u64(),
  answerId: __t.u64(),
  roomId: __t.u64(),
  score: __t.i32(),
  notes: __t.string(),
  source: __t.string(),
  createdAt: __t.timestamp(),
});
export type Feedback = __Infer<typeof Feedback>;

export const Participant = __t.object("Participant", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  role: __t.string(),
  seat: __t.i32(),
  online: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type Participant = __Infer<typeof Participant>;

export const PhaseTick = __t.object("PhaseTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PhaseTick = __Infer<typeof PhaseTick>;

export const Presence = __t.object("Presence", {
  identity: __t.identity(),
  online: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type Presence = __Infer<typeof Presence>;

export const Question = __t.object("Question", {
  id: __t.u64(),
  roomId: __t.u64(),
  text: __t.string(),
  source: __t.string(),
  askedAt: __t.timestamp(),
});
export type Question = __Infer<typeof Question>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  topic: __t.string(),
  status: __t.string(),
  currentQuestionId: __t.option(__t.u64()),
  currentTurn: __t.option(__t.identity()),
  turnStartedAt: __t.option(__t.timestamp()),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const VideoFrame = __t.object("VideoFrame", {
  identity: __t.identity(),
  roomId: __t.u64(),
  data: __t.byteArray(),
  seq: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type VideoFrame = __Infer<typeof VideoFrame>;

